source: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

> from __future__ import print_function  

って必要？

In [1]:
import torch

chainerでいうVariableの定義

In [2]:
x = torch.empty(5, 3)
print(x) # 中身定義しなくても初期化はされる(なんか入ってる)
x = torch.rand(5, 3)
print(x)
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
x = torch.tensor([5.5, 3])
print(x)
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size
print(x.size())
y = torch.rand(5, 3)
print(x + y)
print(torch.add(x, y))
result = torch.empty(5, 3)
print(result)
torch.add(x, y, out=result)
print('りざると')
print(result)
# adds x to y
y.add_(x)
print(y)
print(x[:, 1])

tensor([[7.5563e+31, 1.8014e+25, 8.1335e+32],
        [7.2436e+22, 7.5554e+28, 2.9635e+29],
        [2.2087e+03, 2.9386e+29, 7.1104e-04],
        [1.3556e-19, 1.8567e-01, 2.1017e-19],
        [7.5553e+28, 5.2839e-11, 7.5018e+28]])
tensor([[0.5675, 0.7805, 0.5725],
        [0.2413, 0.3477, 0.5998],
        [0.2134, 0.5371, 0.0527],
        [0.2873, 0.8999, 0.7120],
        [0.4615, 0.3596, 0.2809]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.0248, -2.0738, -0.4935],
        [-0.3784, -0.9650,  1.3495],
        [ 0.2567,  0.1185, -1.1576],
        [-0.2589, -0.8160, -0.9044],
        [ 0.5126,  0.1875,  0.2032]])
torch.Size([5, 3])
tensor([[ 0.0433, -1.8299,  0.4214],
        [-0.2309, -0.5703,  1.4583],
        [ 1.1575,  0.2354, -1.1160],
        [ 0.6390, -0.5230, -0

viewはいわゆるnp.reshape

その他色んなオペレーションは以下に
https://pytorch.org/docs/stable/torch.html

In [3]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

x = torch.randn(1)
print(x)
print(x.item())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([-0.5356])
-0.5355790257453918


In [4]:
# numpyへの橋渡し
type(x.numpy())

numpy.ndarray

In [5]:
b=x.numpy()

In [6]:
x.add_(1)

tensor([0.4644])

In [7]:
 b

array([0.46442097], dtype=float32)

numpyにしてもコピーはとっておらずそのまま参照してるので注意。逆もまた然り。
(torch.from_numpyでやる)

In [8]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [9]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))   

tensor([1.4644], device='cuda:0')
tensor([1.4644], dtype=torch.float64)


In [10]:
torch.cuda.is_available()

True